spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${spring.datasource.host}:5432/test-db
    username: test
    password: test@123
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

management:
  endpoint:
    metrics:
      enabled: true
    caches:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'